import type { Dictionary } from "./types";
export const en: Dictionary = {
  meta: { title: "PT Nanu Tech Solution — Technology That Works", description: "We build software, infrastructure, and digital systems around how organizations actually work." },
  nav: { home: "Home", solutions: "Capabilities", industries: "Context", work: "Experience", about: "About", contact: "Let's talk", cta: "Let's talk" },
  ui: { menuOpen: "Open navigation", menuClose: "Close navigation", skip: "Skip to main content", connected: "SYSTEM CONNECTED", selectedExperience: "SELECTED EXPERIENCE", founderExperience: "FOUNDER EXPERIENCE", systemMap: "SYSTEM MAP", systemMapDescription: "The relationship between people, process, data, systems, and decisions.", securityArchitecture: "SECURITY ARCHITECTURE", securityArchitectureDescription: "Control layers that keep systems accessible, traceable, and recoverable.", capabilityIndex: "CAPABILITY INDEX", stackTitle: "ENGINEERING STACK", stackDescription: "Technology selected for the system, not the trend.", footerSolutions: "SOLUTIONS", footerConnect: "CONNECT", footerSystem: "SYSTEM", unavailable: "To be confirmed" },
  hero: { eyebrow: "PT NANU TECH SOLUTION / TECHNOLOGY PARTNER", title: "We build technology around how organizations actually work.", text: "Software, systems, infrastructure, and digital solutions designed around real operational processes.", primary: "Start with the problem", secondary: "Explore capabilities", flow: ["People", "Process", "Data", "System", "Decisions"] },
  sections: { solutions: "Systems for real problems", industries: "Context shapes the system", cooperative: "Cooperative technology, from members to management", education: "A connected education ecosystem", work: "Selected Work", experience: "Professional Experience & Selected Work", process: "How we work", security: "Security by Design", about: "About PT Nanu Tech Solution", principles: "Our principles", contact: "Have a system that needs to work better?" },
  solutions: [
    { title: "Software Systems", text: "Applications shaped around workflows, users, and the operational decisions an organization needs to make." },
    { title: "Digital Infrastructure", text: "Cloud, servers, deployment, backup, and monitoring for systems ready to operate." },
    { title: "Data & Information", text: "Dashboards, reporting, integration, and structured information for clearer decisions." },
    { title: "Connected Systems", text: "Device integration, IoT, automation, and systems that connect digital work to the real world." },
    { title: "Security & Auditability", text: "Authentication, authorization, access control, audit trails, and operational protection from the start." }
  ],
  industries: [{ title: "Cooperatives", text: "Member services, savings and loans, staff operations, branches, and reporting." }, { title: "Education", text: "Academic systems, admissions, course registration, scheduling, administration, and reporting." }, { title: "Business", text: "Business systems, workflows, management information, and integrations built for your needs." }, { title: "Organizations & Institutions", text: "Digital administration, documents, reporting, and more connected operational systems." }],
  cooperative: [{ title: "Member Platform", text: "Profiles, savings, loans, installments, notifications, and service requests." }, { title: "Staff Platform", text: "Member management, verification, transactions, and collection." }, { title: "Management Dashboard", text: "Member overview, portfolio, branches, and reports." }, { title: "Digital Archive", text: "Documents, history, search, and administration." }],
  education: ["Academic Information System", "Admissions", "Course Registration", "Curriculum", "Scheduling", "Student Administration", "Academic Reporting", "Management Dashboards"],
  work: [{ title: "SIAKAD UNMARIS", text: "A digital academic ecosystem covering student administration, curriculum, course registration, scheduling, academic workflows, and management reporting." }, { title: "Cooperative Digital Platform", text: "A digital platform concept for cooperative members, staff, and management." }, { title: "Executive Dashboard", text: "A concept for operational and management monitoring." }, { title: "Custom Business Applications", text: "Systems built around real operational workflows." }],
  process: [{ title: "Understand", text: "Understand the problem and business process." }, { title: "Analyze", text: "Analyze requirements, risks, and workflows." }, { title: "Design", text: "Design architecture, database, UX, and workflow." }, { title: "Build", text: "Develop the solution incrementally." }, { title: "Test", text: "Test functionality, usability, and operational readiness." }, { title: "Deploy", text: "Deploy the solution into production." }, { title: "Support", text: "Maintain, monitor, and improve." }],
  security: ["Access control", "Auditability", "Data protection", "Backup", "Monitoring", "Infrastructure security"],
  securityFlow: ["User", "Authentication", "Authorization", "Application", "Database", "Backup", "Monitoring"],
  stack: [{ label: "APPLICATION", items: ["Laravel", "PHP", "Flutter", "REST API"] }, { label: "DATA", items: ["MySQL", "Redis", "Structured Data"] }, { label: "INFRASTRUCTURE", items: ["Linux", "VPS", "Cloud", "Networking"] }, { label: "SECURITY", items: ["Authentication", "Authorization", "Backup", "Audit Trail"] }],
  about: "PT Nanu Tech Solution is a technology company focused on building practical digital solutions for organizations and businesses. We build technology around your problems, processes, data, users, and working context.",
  experience: { title: "Professional Experience & Selected Work", disclaimer: "The experience below represents professional and founder experience. Not all work is an official PT Nanu Tech Solution project.", items: [{ title: "Full-stack Developer", text: "Full-stack development experience at RS Karitas." }, { title: "Backend Developer", text: "Backend development experience at PT MBT Yogyakarta." }, { title: "SIAKAD Development", text: "Developed a complete academic information system for UNMARIS." }, { title: "News Portals", text: "Developed news portals for siletsumba.com, highlightntt.com, lionnews.id, and nusaaksaranews.com." }] },
  principles: [{ title: "Practical", text: "Technology must solve real problems." }, { title: "Secure", text: "Security is part of the architecture." }, { title: "Scalable", text: "Systems should grow with the organization." }, { title: "Transparent", text: "Important activities should be traceable." }, { title: "Maintainable", text: "Systems must remain understandable and maintainable." }, { title: "Human-Centered", text: "Technology should make work easier." }],
  cta: { title: "Let's build something that works.", text: "Tell us about the operational process you want to improve, and let's start with the problem.", button: "Start a conversation" },
  contact: { title: "Start with the problem", text: "Tell us about your organization's needs and challenges.", email: "[EMAIL]", phone: "[PHONE]", location: "Indonesia", note: "Contact details will be updated once confirmed." },
  footer: "Technology That Works. Solutions That Matter."
};
