import type { Dictionary } from "./types";
export const id: Dictionary = {
  meta: { title: "PT Nanu Tech Solution — Teknologi yang Bekerja", description: "Kami membangun perangkat lunak, infrastruktur, dan sistem digital berdasarkan cara organisasi benar-benar bekerja." },
  nav: { home: "Beranda", solutions: "Kapabilitas", industries: "Konteks", work: "Pengalaman", about: "Tentang", contact: "Mari bicara", cta: "Mari bicara" },
  ui: { menuOpen: "Buka navigasi", menuClose: "Tutup navigasi", skip: "Lewati ke konten utama", connected: "SISTEM TERHUBUNG", selectedExperience: "PENGALAMAN TERPILIH", founderExperience: "PENGALAMAN PENDIRI", systemMap: "PETA SISTEM", systemMapDescription: "Hubungan antara orang, proses, data, sistem, dan keputusan.", securityArchitecture: "ARSITEKTUR KEAMANAN", securityArchitectureDescription: "Lapisan kontrol yang menjaga sistem dapat diakses, ditelusuri, dan dipulihkan.", capabilityIndex: "INDEKS KAPABILITAS", stackTitle: "ENGINEERING STACK", stackDescription: "Teknologi dipilih berdasarkan kebutuhan sistem, bukan tren.", footerSolutions: "SOLUSI", footerConnect: "TERHUBUNG", footerSystem: "SISTEM", unavailable: "Segera dikonfirmasi" },
  hero: { eyebrow: "PT NANU TECH SOLUTION / TECHNOLOGY PARTNER", title: "Kami membangun teknologi berdasarkan cara organisasi benar-benar bekerja.", text: "Perangkat lunak, sistem, infrastruktur, dan solusi digital yang dirancang untuk proses operasional nyata.", primary: "Mulai dari masalahnya", secondary: "Lihat kapabilitas", flow: ["Orang", "Proses", "Data", "Sistem", "Keputusan"] },
  sections: { solutions: "Sistem untuk masalah nyata", industries: "Konteks menentukan sistem", cooperative: "Teknologi koperasi, dari anggota hingga manajemen", education: "Ekosistem pendidikan yang terhubung", work: "Pengalaman Terpilih", experience: "Pengalaman Profesional & Karya Terpilih", process: "Cara kami bekerja", security: "Security by Design", about: "Tentang PT Nanu Tech Solution", principles: "Prinsip kami", contact: "Punya sistem yang perlu bekerja lebih baik?" },
  solutions: [
    { title: "Software Systems", text: "Aplikasi yang mengikuti alur kerja, kebutuhan pengguna, dan keputusan operasional organisasi." },
    { title: "Digital Infrastructure", text: "Cloud, server, deployment, pencadangan, dan pemantauan untuk sistem yang siap digunakan." },
    { title: "Data & Information", text: "Dashboard, pelaporan, integrasi, dan informasi terstruktur untuk keputusan yang lebih jelas." },
    { title: "Connected Systems", text: "Integrasi perangkat, IoT, otomasi, dan sistem yang menghubungkan aktivitas nyata." },
    { title: "Security & Auditability", text: "Otentikasi, otorisasi, hak akses, audit trail, dan perlindungan operasional sejak awal." }
  ],
  industries: [{ title: "Koperasi", text: "Layanan anggota, simpan pinjam, operasional staf, cabang, dan pelaporan." }, { title: "Pendidikan", text: "Sistem akademik, penerimaan, KRS, penjadwalan, administrasi, dan pelaporan." }, { title: "Bisnis", text: "Sistem bisnis, alur kerja, informasi manajemen, dan integrasi yang sesuai kebutuhan." }, { title: "Organisasi & Institusi", text: "Administrasi digital, dokumen, pelaporan, dan sistem operasional yang lebih terhubung." }],
  cooperative: [{ title: "Platform Anggota", text: "Profil, simpanan, pinjaman, angsuran, notifikasi, dan permintaan layanan." }, { title: "Platform Staf", text: "Pengelolaan anggota, verifikasi, transaksi, dan penagihan." }, { title: "Dashboard Manajemen", text: "Ringkasan anggota, portofolio, cabang, dan laporan." }, { title: "Arsip Digital", text: "Dokumen, riwayat, pencarian, dan administrasi." }],
  education: ["SIAKAD", "PMB", "KRS", "Kurikulum", "Penjadwalan", "Administrasi Mahasiswa", "Pelaporan Akademik", "Dashboard Manajemen"],
  work: [{ title: "SIAKAD UNMARIS", text: "Ekosistem akademik digital yang mencakup administrasi mahasiswa, kurikulum, KRS, penjadwalan, alur akademik, dan pelaporan manajemen." }, { title: "Platform Digital Koperasi", text: "Konsep platform digital untuk anggota, staf, dan manajemen koperasi." }, { title: "Dashboard Eksekutif", text: "Konsep pemantauan operasional dan informasi manajemen." }, { title: "Aplikasi Bisnis Kustom", text: "Sistem yang dibangun mengikuti alur kerja operasional yang nyata." }],
  process: [{ title: "Pahami", text: "Memahami masalah dan proses bisnis." }, { title: "Analisis", text: "Menganalisis kebutuhan, risiko, dan alur kerja." }, { title: "Rancang", text: "Merancang arsitektur, database, UX, dan alur." }, { title: "Bangun", text: "Mengembangkan solusi secara bertahap." }, { title: "Uji", text: "Menguji fungsi, kegunaan, dan kesiapan operasional." }, { title: "Terapkan", text: "Menerapkan solusi ke lingkungan produksi." }, { title: "Dukung", text: "Memelihara, memantau, dan terus memperbaiki." }],
  security: ["Kontrol akses", "Auditabilitas", "Perlindungan data", "Pencadangan", "Pemantauan", "Keamanan infrastruktur"],
  securityFlow: ["Pengguna", "Otentikasi", "Otorisasi", "Aplikasi", "Database", "Backup", "Monitoring"],
  stack: [{ label: "APLIKASI", items: ["Laravel", "PHP", "Flutter", "REST API"] }, { label: "DATA", items: ["MySQL", "Redis", "Structured Data"] }, { label: "INFRASTRUKTUR", items: ["Linux", "VPS", "Cloud", "Networking"] }, { label: "KEAMANAN", items: ["Authentication", "Authorization", "Backup", "Audit Trail"] }],
  about: "PT Nanu Tech Solution adalah perusahaan teknologi yang berfokus membangun solusi digital praktis untuk organisasi dan bisnis. Kami membangun teknologi berdasarkan masalah, proses, data, pengguna, dan konteks kerja Anda.",
  experience: { title: "Pengalaman Profesional & Karya Terpilih", disclaimer: "Pengalaman berikut merupakan pengalaman profesional dan karya pendiri. Tidak semuanya merupakan proyek resmi PT Nanu Tech Solution.", items: [{ title: "Full-stack Developer", text: "Pengalaman mengembangkan solusi full-stack di RS Karitas." }, { title: "Backend Developer", text: "Pengalaman bekerja sebagai backend developer di PT MBT Yogyakarta." }, { title: "Pengembangan SIAKAD", text: "Mengembangkan sistem informasi akademik lengkap untuk UNMARIS." }, { title: "Portal Berita", text: "Mengembangkan portal berita untuk siletsumba.com, highlightntt.com, lionnews.id, dan nusaaksaranews.com." }] },
  principles: [{ title: "Praktis", text: "Teknologi harus menyelesaikan masalah nyata." }, { title: "Aman", text: "Keamanan menjadi bagian dari arsitektur." }, { title: "Skalabel", text: "Sistem siap tumbuh bersama organisasi." }, { title: "Transparan", text: "Aktivitas penting harus dapat ditelusuri." }, { title: "Mudah Dirawat", text: "Sistem harus tetap dipahami dan dipelihara." }, { title: "Berpusat pada Manusia", text: "Teknologi harus membuat pekerjaan lebih mudah." }],
  cta: { title: "Mari membangun sesuatu yang benar-benar bekerja.", text: "Ceritakan proses operasional yang ingin Anda perbaiki, lalu kita mulai dari masalahnya.", button: "Mulai percakapan" },
  contact: { title: "Mari mulai dari masalahnya", text: "Ceritakan kebutuhan dan tantangan organisasi Anda.", email: "contact@nanutechsolution.com", phone: "Kirim email", location: "Indonesia", note: "Pesan akan diproses melalui email resmi PT Nanu Tech Solution." },
  footer: "Teknologi yang Bekerja. Solusi yang Berdampak."
};
